version: '3'

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    command: yarn serve

  server:
    build: ./server
    ports:
      - 8888:8888
    volumes:
      - ./server:/app
    command: fresh

  postgres:
    container_name: postgres
    build: ./postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=Othello
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Othello